export default [
    'CHANGE_BASE_COLOR',
    'ADD_SHAPE',
    'DELETE_SELECTED_SHAPE',
    'SELECT_SHAPE',
    'DESELECT_ALL',
    'SELECTED_SHAPE_UP',
    'SELECTED_SHAPE_DOWN',
    'CHANGE_SHAPE_TRANSLATION',
    'CHANGE_SELECTED_COLOR',
    'SET_ALL_SHAPES',
    'PASTE_FROM_CLIPBOARD',
    'CHANGE_PASTED_SCALE'
];
